---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: store-host
  annotations:
    external-dns.ambassador-service: emissary-emissary-ingress.platform
spec:
  hostname: store.app.me
  tlsSecret:
    name: selfsigned-tls
  requestPolicy:
    insecure:
      action: Redirect