---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: linkerd-dashboard-host
  annotations:
    external-dns.ambassador-service: emissary-emissary-ingress.platform
spec:
  hostname: mesh.app.me
  tlsSecret:
    name: selfsigned-tls
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: grafana-host
  annotations:
    external-dns.ambassador-service: emissary-emissary-ingress.platform
spec:
  hostname: monitoring.app.me
  tlsSecret:
    name: selfsigned-tls
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: prometheus-server-host
  annotations:
    external-dns.ambassador-service: emissary-emissary-ingress.platform
spec:
  hostname: metrics.app.me
  tlsSecret:
    name: selfsigned-tls
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: hubble-host
  annotations:
    external-dns.ambassador-service: emissary-emissary-ingress.platform
spec:
  hostname: network.app.me
  tlsSecret:
    name: selfsigned-tls
  requestPolicy:
    insecure:
      action: Redirect