---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: app-map
spec:
  hostname: app.me
  prefix: /
  add_request_headers:
    Knative-Serving-Revision:
      value: "nginx-00001"
    Knative-Serving-Namespace:
      value: "knative-serving"
  service: nginx-00001.app.svc.cluster.local
  timeout_ms: 180000 # 3 minutes
  bypass_auth: true