---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: app-map
spec:
  hostname: app.me
  prefix: /service-a
  service: keda-add-ons-http-interceptor-proxy.keda:8080 #nginx-service.app
  timeout_ms: 180000 # 3 minutes
  bypass_auth: true