# ---
# apiVersion: getambassador.io/v3alpha1
# kind: Mapping
# metadata:
#   name: app-map
# spec:
#   hostname: app.me
#   prefix: /
#   service: keda-add-ons-http-interceptor-proxy.keda:8080 #nginx-service.app
#   timeout_ms: 180000 # 3 minutes
#   bypass_auth: true
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: app-map
spec:
  hostname: app.me
  prefix: /
  service: nginx-service.app
  timeout_ms: 180000 # 3 minutes
  bypass_auth: true
  labels:
    emissary:
      # - request_label_group:
      #   - x-emissary-test-allow:
      #     request_headers:
      #       key: "x-emissary-test-allow"
      #       header_name: "x-emissary-test-allow"
      - request_label_group:
        - x-forwarded-for:
          request_headers:
            key: "x-forwarded-for"
            header_name: "x-forwarded-for"

