---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: store-map
spec:
  hostname: store.app.me
  prefix: /
  service: frontend.app
  timeout_ms: 180000 # 3 minutes
  bypass_auth: true