apiVersion: v1
kind: Service
metadata:
  name: ratelimit-service
  namespace: platform
spec:
  selector:
    app: ratelimit-service
  ports:
    - name: http
      port: 5000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-service
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-service
  template:
    metadata:
      labels:
        app: ratelimit-service
    spec:
      containers:
      - name: ratelimit-service
        env:
          - name: ALLOWED_IPS
            value: 192.168.1.100,10.0.0.0/24,172.18.0.1
          - name: DENIED_IPS
            value: "192.168.1.101"
        image: ratelimit-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 5000
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimitService
metadata:
  name: ratelimit-service
  namespace: platform
spec:
  service: "ratelimit-service.platform:5000"
  protocol_version: v3 # Required in emissary-ingress v3.0.0+
  domain: emissary # override defaul "ratelimt" domain see docs for details
  failure_mode_deny: true # forces 500 response if unable to talk with RateLimitService